### ISSUE TITLE
微信文章命令demo参数写错了

### ISSUE THREAD

**Issue by idlefire** [woodpecker-framework/ysoserial-for-woodpecker#3]
https://mp.weixin.qq.com/s/wvKfe4xxNXWEgtQE4PdTaQ
应该是 `-a`
![image](https://user-images.githubusercontent.com/18007341/127946080-4174356d-e527-42cb-a1d1-c63754afa5b0.png)

**Comment by c0ny1** [comment]
嗯，确实写错了。这个会在blog修正，公众号发布的文章已经无法更改图片。
